[app]
; Путь к сетевой папке с ресурсами (буллеты, иконки, баннеры, config.json)
; network_path = \\gd.rt.ru\dfs\BORUP\BORUP02\ДЕПАРТАМЕНТ УПРАВЛЕНИЯ ЗНАНИЯМИ\PR\Конструктор писем\server\email-builder
network_path = \\ks.rt.ru\dfs\BORUP\BORUP11\Отчет обученности Робот\server\email-builder

; Порт локального сервера
port = 8080

